# Generated by Django 5.2.6 on 2025-09-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default=None, max_length=15, unique=True),
        ),
    ]
