# Generated by Django 5.2.6 on 2025-09-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_userprofile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='role',
            new_name='title',
        ),
        migrations.AddField(
            model_name='experience',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('self_employed', 'Self-employed'), ('freelance', 'Freelance'), ('contract', 'Contract'), ('internship', 'Internship'), ('apprenticeship', 'Apprenticeship'), ('seasonal', 'Seasonal'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='location_type',
            field=models.CharField(blank=True, choices=[('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=20, null=True),
        ),
    ]
