# Generated by Django 5.2.6 on 2025-09-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_role_experience_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='employment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
