# Generated by Django 5.2.6 on 2025-09-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_headline',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
