# Generated by Django 5.2.6 on 2025-10-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_connection_connectionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/default-profile.png', null=True, upload_to='profile_photos/'),
        ),
    ]
