# Generated by Django 5.2.6 on 2025-10-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(default='profile_photos/default-profile.png', upload_to='profile_photos/'),
        ),
    ]
